In [38]:
#Лабораторна робота №3 Елементи лінійної алгебри. Розв’язання систем лінійних алгебраїчних рівнянь
#Варіант 1
#Галатенко Дарія Іванівна 2-16
#Завдання 1 (приклад 2)
#Знайти матрицю C = AB-BA 

import numpy as np
A = np.array([[2, 3, 1], [-1, 1, 0], [1, 2, -1]])
print("Матриця A:")
print(A)
B = np.array([[1, 2, 1], [0, 1, 2], [3, 1, 1]])
print("Матриця B:")
print(B)
# Обчислення добутків AB та BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Обчислення матриці C = AB - BA
C = AB - BA

print("Матриця C = AB - BA:")
print(C)

Матриця A:
[[ 2  3  1]
 [-1  1  0]
 [ 1  2 -1]]
Матриця B:
[[1 2 1]
 [0 1 2]
 [3 1 1]]
Матриця C = AB - BA:
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [5]:
#Завдання 2 (приклад 2)
#Піднести матрицю до степеня
A = np.array([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])
print("Матриця A:")
print(A)
# Підносимо матрицю A до степеня 2
result = np.linalg.matrix_power(A, 2)

print(f"Матриця A^2:")
print(result)

Матриця A:
[[-1  0  2]
 [ 0  1  0]
 [ 1  2 -1]]
Матриця A^2:
[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [9]:
#Завдання 3 (приклад 3)
#Знайти добуток матриць
A = np.array([[3, 0, 7], [-4, 2, 3], [-1, 1, 2]])
print("Матриця A:")
print(A)
B = np.array([[1], [2], [4]])
print("Матриця B:")
print(B)
AB = np.dot(A, B)
print("Добуток AB:")
print(AB)

Матриця A:
[[ 3  0  7]
 [-4  2  3]
 [-1  1  2]]
Матриця B:
[[1]
 [2]
 [4]]
Добуток AB:
[[31]
 [12]
 [ 9]]


In [13]:
#Завдання 4 (приклад 4)
#Обчислити визначник
A = np.array([[1, 2, 3], [-1, 2, 1], [1, 3, 2]])
print("Матриця A:")
print(A)
A_det = np.linalg.det(A)
print("Визначник матриці:")
print(format(A_det, '.9g'))

Матриця A:
[[ 1  2  3]
 [-1  2  1]
 [ 1  3  2]]
Визначник матриці:
-8


In [15]:
#Завдання 5 (приклад 2)
#Обчислити визначник
A = np.array([[2, 3, 4, 1], [1, 2, 3, 4], [3, 4, 1, 2], [4, 1, 2, 3]])
print("Матриця A:")
print(A)
A_det = np.linalg.det(A)
print("Визначник матриці:")
print(format(A_det, '.9g'))

Матриця A:
[[2 3 4 1]
 [1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]]
Визначник матриці:
-160


In [17]:
#Завдання 6 (приклад 1)
#Знайти обернену матрицю до матриці
A = np.array([[1, 2, -3], [0, 1, 2], [0, 0, 1]])
print("Матриця A:")
print(A)
A_inv = np.linalg.inv(A).astype(int)
print("Обернена матриця:")
print(A_inv)

Матриця A:
[[ 1  2 -3]
 [ 0  1  2]
 [ 0  0  1]]
Обернена матриця:
[[ 1 -2  7]
 [ 0  1 -2]
 [ 0  0  1]]


In [18]:
#Завдання 7 (приклад 3)
#Визначити ранг матриці
A = np.array([[-2, 3, 1, -1], [3, 2, 1, 4], [1, 2, 3, 4], [0, 2, 3, 3]])
print("Матриця A:")
print(A)
rank = np.linalg.matrix_rank(A)
print("Ранг матриці:")
print(rank)


Матриця A:
[[-2  3  1 -1]
 [ 3  2  1  4]
 [ 1  2  3  4]
 [ 0  2  3  3]]
Ранг матриці:
3


In [37]:
#Завдання 8 (Варіант 1)
#Розв’язати систему лінійних рівнянь методом Крамера, матричним
#методом (тобто обчислити обернену матрицю) і м. Гауса. Потім
#зробити перевірку за допомогою solve() пакету linalg :
# Задаємо коефіцієнти системи рівнянь у вигляді матриці A та вектора b
A = np.array([[14, 4, 6], [5, -3, 2], [10, -11, 5]])
b = np.array([30, 15, 36])

# Метод Крамера
def kramer_method(A, b):
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0):
        print("Система рівнянь не має однозначного розв'язку (визначник A = 0).")
        return None
    x = np.zeros_like(b, dtype=float)
    for i in range(len(b)):
        A_temp = A.copy()
        A_temp[:, i] = b
        x[i] = np.linalg.det(A_temp) / det_A
    return x

# Матричний метод (обчислення оберненої матриці)
def matrix_method(A, b):
    A_inv = np.linalg.inv(A)
    x = np.dot(A_inv, b)
    return x

# Метод Гауса
def gaussian_elimination(A, b):
    augmented_matrix = np.column_stack((A, b))
    n = len(b)
    for i in range(n):
        # Перевірка чи діагональний елемент не нульовий
        if augmented_matrix[i, i] == 0:
            print("Система рівнянь не має однозначного розв'язку (діагональний елемент нуль).")
            return None
        # Нормалізація рядка
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]
        # Віднімання нормалізованого рядка від інших рядків
        for j in range(n):
            if i != j:
                augmented_matrix[j] -= augmented_matrix[i] * augmented_matrix[j, i]
    x = augmented_matrix[:, -1]
    return x

# Результати рішення за різними методами
print("Розв'язок за допомогою методу Крамера:", kramer_method(A, b))
print("Розв'язок за допомогою матричного методу (обернена матриця):", matrix_method(A, b))
print("Розв'язок за допомогою методу Гауса:", gaussian_elimination(A, b))

# Перевірка за допомогою solve()
x_check = np.linalg.solve(A, b)
print("Перевірка за допомогою solve():", x_check)

Розв'язок за допомогою методу Крамера: [ 2. -1.  1.]
Розв'язок за допомогою матричного методу (обернена матриця): [ 2. -1.  1.]
Розв'язок за допомогою методу Гауса: [ 2 -1  1]
Перевірка за допомогою solve(): [ 2. -1.  1.]


In [45]:
#Завдання
#6) Створіть прямокутну матрицю A, яка має N рядків і стовпці M з
#випадковими елементами. Визначте, скільки негативних елементів міститься
#в кожному стовпці та в кожному рядку матриці.

def count_negative_elements(matrix):
    # Кількість негативних елементів в кожному стовпці
    column_negatives = np.sum(matrix < 0, axis=0)
    # Кількість негативних елементів в кожному рядку
    line_negatives = np.sum(matrix < 0, axis=1)
    return column_negatives, line_negatives

def main():
    # Створення прямокутної матриці з випадковими цілими числами
    A = np.random.randint(-10, 10, size=(3, 3))
    print("Прямокутна матриця A:")
    print(A)
    
    # Обчислення кількості негативних елементів в кожному стовпці і рядку
    column_negatives, line_negatives = count_negative_elements(A)
    print("Кількість негативних елементів в кожному стовпці:")
    print(column_negatives)
    print("Кількість негативних елементів в кожному рядку:")
    print(line_negatives)

if __name__ == "__main__":
    main()

Прямокутна матриця A:
[[  8  -5   6]
 [  2   3   9]
 [ -5 -10  -4]]
Кількість негативних елементів в кожному стовпці:
[1 2 1]
Кількість негативних елементів в кожному рядку:
[1 0 3]


In [41]:
#Висновок: Завдяки виконанню цієї лабораторної роботи я отримала цінний досвід у вирішенні різноманітних завдань 
#з лінійної алгебри та роботи з матрицями. В процесі виконання було вивчено та застосовано різні методи, 
#такі як матричний метод, метод Крамера та метод Гауса для розв'язання систем лінійних рівнянь.
#Я впевнена, що отримані навички будуть корисними для мене у подальших студентських та професійних проектах, 
#де потрібно буде вирішувати складні математичні задачі.